#!/usr/bin/env bash
# create web server 1. Install nginx web server
sudo apt-get update -y
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
