#!/usr/bin/env bash
# 3. Redirection
sudo apt-get update -y
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "42i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent\
;" /etc/nginx/sites-available/default
sudo service nginx start
