#!/usr/bin/env bash
# 4. Not found page 404
# shellcheck disable=SC2154
sudo apt-get update -y
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "42i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent\
;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/error/404.html
sudo sed -i "49i \\\terror_page 404 /404.html;\n\tlocation  /404.html {\n\t\troot /var/www/error/;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
sudo service nginx start
