#!/usr/bin/env bash
# Install your load balancer
sudo apt-get update

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt-get update
sudo apt-get install -y haproxy=1.7.\*

echo -e "

frontend http\n\
\tbind *:80\n\
\tmode http\n\
\tdefault_backend web-backend

backend web-backend\n
\tbalance roundrobin\n\
\tserver 731-web-01 35.231.233.196:80 check\n\
\tserver 731-web-02 35.190.169.220:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
sudo service haproxy reload
