#!/usr/bin/env bash
#2. 7 lines or less
chown nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx stop
sed -i 's/80 /8080 /g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
